### PR TITLE
Fixed wrong page opening for bus ticket buying

### LINKED ISSUE #876: Wrong page opening for bus ticket buying
@ankit071105 The sell train ticket page is getting opened when we click on sell bus ticket, please assign this to me and do add the lables like gsooc-ext, gssoc, hackoberfest.

Please find attached.
Thank you!

https://github.com/user-attachments/assets/ebf49761-4719-43ff-b373-d44546b1d576

### PR DESCRIPTION
**Pull request by saatvika07**
Changed the href tag from sell.html to sell_bus_ticket.html
## What does this PR do?
This PR changes the sell bus tickets page.

Fixes #876

Screenshot 2024-11-03 203255

### CODE REVIEW

**Comment by saatvika07** [comment]
Please look at this pull request!

**Comment by ankit071105** [comment]
Resolve the conflicts

**Comment by saatvika07** [comment]
Resolved the issues please look into it and let me know!
Thank you!

**Comment by saatvika07** [comment]
Please add level 3 label as I have added a new named sell_bus_ticket making it precise for bus transport. Thank you!

**Comment by saatvika07** [comment]
Please add level 3 label as I have added a new named sell_bus_ticket making it precise for bus transport. Thank you!

**Comment by saatvika07** [comment]
All conflicts are resolved please check and add the suitable level tag as i created a new functionality of sell_bus_ticket. Thank you!

**Pull request closed without merging**
