### PR TITLE
To adding the animation effect to social media icons 

### PR DESCRIPTION
**Pull request by Sujal1201**
## Issue: animation effect on social media icons

**before**

https://github.com/user-attachments/assets/d0579d85-711b-4bab-8bf4-2103779072cb

**after**

https://github.com/user-attachments/assets/bec5e3be-b900-4d54-9cf0-e1f26d61e1ab

**issue #816

### CODE REVIEW

**Comment by Sujal1201** [comment]
please give me level 2 tag

**Comment by ankit071105** [comment]
Resolve the conflicts

**Comment by Sujal1201** [comment]
I Solve the conflicts

**Comment by Sujal1201** [comment]
please give me level 2 tag

**Comment by ankit071105** [comment]
Resolve the conflicts

**Comment by Sujal1201** [comment]
Sorry for the late I resolve the  conflicts

**Comment by Sujal1201** [comment]
please give me level 2 tag

**Pull request merged**
