### PR TITLE
Google Authorization Done

### LINKED ISSUE #873: Incomplete registration with google
"Continue with google" is not working in the website. It does not redirect to any page after clicking. User can not register with google account then. Please assign this to me with proper level.

### PR DESCRIPTION
**Pull request by sayanp607**
## What does this PR do?
this helps user to login with their google account.

Fixes #873 

## Type of change

- New feature (non-breaking change which adds functionality)

## Mandatory Tasks

- [.] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by Leoawad — COMMENTED** [review]
The red color is for errors or I am wrong.

**Comment by ankit071105** [comment]
Resolve the conflicts

**Comment by sayanp607** [comment]
> Resolve the conflicts

done

**Comment by ankit071105** [comment]
Resolve the conflicts

**Comment by sayanp607** [comment]
> Resolve the conflicts

done

**Pull request closed without merging**
