### PR TITLE
Register page done

### LINKED ISSUE #871: Improper logic in sign up page.
Screenshot 2024-11-01 143755
it's happening because of the incomplete and improper logic in js. Please assign this to me with proper level badge. I will fix it.

### PR DESCRIPTION
**Pull request by sayanp607**
## What does this PR do?

this helps user to register them selves properly and shows notifications. 

Fixes #871

Uploading Screen Recording 2024-11-03 202216.mp4…
## Type of change

- New feature (non-breaking change which adds functionality)

## Mandatory Tasks

- [. ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected

### CODE REVIEW

**Comment by ankit071105** [comment]
Resolve the conflicts

**Comment by sayanp607** [comment]
> Resolve the conflicts

done

**Comment by ankit071105** [comment]
Resolve the conflicts

**Comment by sayanp607** [comment]
> Resolve the conflicts

done
merge it kindly.

**Pull request merged**
