### PR TITLE
Adding the AsyncHandler,ApiResponse,ApiError Utility and Making Desir…

### PR DESCRIPTION
**Pull request by MOHINI1403**
### Changes Made: 
- Adding the common utility for the AsyncHandler this is for handling and avoiding writing try...catch block again and again for every controller.
- Adding the common utility for ApiResponse and ApiError so that both of them are following the standard format all over the code base.
- Making changes into the `Register` Controller and the `Login` Controller as desired.
- Modifying the format of code over there and adding comments wherever necessary 

## How I am Making Contribution:
I am making this contribution under `GSsOC-Exd`

Please consider the desired changes into the pull request in response to the issue :
[Issue Link ](https://github.com/ankit071105/Ticket-Booking/issues/88)

### CODE REVIEW

**Comment by ankit071105** [comment]
> ## Addition of Common Utility code and Making the Desired Changes
> ### Changes Made:
> * Adding the common utility for the AsyncHandler this is for handling and avoiding writing try...catch block again and again for every controller.
> * Adding the common utility for ApiResponse and ApiError so that both of them are following the standard format all over the code base.
> * Making changes into the `Register` Controller and the `Login` Controller as desired.
> * Modifying the format of code over there and adding comments wherever necessary
> 
> ## How I am Making Contribution:
> I am making this contribution under `GSsOC-Exd`
> 
> Please consider the desired changes into the pull request in response to the issue : [Issue Link ](https://github.com/ankit071105/Ticket-Booking/issues/88)

Have we assigned you this if yes mention the issue number or else follow the guidelines of the GSSOC-EXTEND and HSCKTOBERFEST

**Comment by MOHINI1403** [comment]
Yes you have assigned me this issue I have also attached the issue link into the description of the PR .
The issue number is #88

**Comment by ankit071105** [comment]
https://chat.whatsapp.com/JWfNTvpbNTfDp0zWsgNGWi 
 you can join us we will have discussion related to our projects in this group. @MOHINI1403

**Comment by MOHINI1403** [comment]
Thank you I joined the group looking forward to work more onto the projects.

**Pull request merged**
