### PR TITLE
FIXED - Non-Redirecting "Top Hotels" Footer Link

### LINKED ISSUE #395: [BUG] Non-Redirecting "Top Hotels" Footer Link
### Description

The footer of the website includes a "Top Hotels" option that is currently not redirecting users to any page or content. This functionality is essential for guiding users to explore popular hotel listings. To resolve this issue, I plan to create a dedicated page featuring various hotels categorized by states in India. Each hotel listed will have a link directing users to its location on Google Maps, ensuring a seamless browsing experience and allowing users to find their desired accommodations easily.

### Screenshots

_No response_

### Any additional information?

_No response_

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by ghost**
## What does this PR do?

This PR fixes the issue where the "Top Hotels" option in the website's footer was not redirecting users to any content. A dedicated page has been created that features a list of top hotels categorized by Indian states. Each hotel card now includes a clickable link that redirects users to the hotel's respective location on Google Maps, allowing for easy navigation. Visual enhancements include ribbons indicating the hotel's location, star ratings, and hover effects for an improved user experience.

## Images/Videos

https://github.com/user-attachments/assets/614301ac-0d0f-4a76-ac10-3f781244d090

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## Mandatory Tasks

- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by snehhhcodes** [comment]
@ankit071105 please review these PR once and will be great if you can label it under level 3 as i created a whole separate page with all the necessary features in it

**Comment by snehhhcodes** [comment]
@ankit071105 assign me #461 #465 #466 as well

**Comment by ankit071105** [comment]
Sorry By mistake it was assigned to you because our webpage doesnt contains any hotel it is for o nly ticket booking purposes

**Comment by snehhhcodes** [comment]
> Sorry By mistake it was assigned to you because our webpage doesnt contains any hotel it is for o nly ticket booking purposes

it does have in footer i think thts why i raised issue and after making PR you are stating it isnt it unfair?

**Comment by ankit071105** [comment]
You can raise any ohter issue only not raise any issue related to hotels and all

**Comment by MastanSayyad** [comment]
@ankit071105 You should be more active while assigning issues, Contributors work hard to create one PR and we told them start working only if they get assign, and they do it too. 

You should not overlook someone's hardwork, you can merge this PR and give her the required labels i.e. level 2 and revert the changes back. 

As most of the Contributors are beginners they dont know these things are part of the open source, as it is the first time, you may explain them and tell for now you will merge this and from next time you should be prepare that these things will happen in future.

**Comment by ankit071105** [comment]
> @ankit071105 You should be more active while assigning issues, Contributors work hard to create one PR and we told them start working only if they get assign, and they do it too.
> 
> You should not overlook someone's hardwork, you can merge this PR and give her the required labels i.e. level 2 and revert the changes back.
> 
> As most of the Contributors are beginners they dont know these things are part of the open source, as it is the first time, you may explain them and tell for now you will merge this and from next time you should be prepare that these things will happen in future.

Who are you brother ? why you  invoving in this matter @MastanSayyad  . The issue was by mistake assign because daily 30+ issue are raising so it get assigned with the flow with the mentor firstly and you dont guide us what to do you we are providing a experienced label and gssoc and hacktoberfest badges. So please dont teach us .

**Comment by ankit071105** [comment]
@snehhhcodes  I am giving you an issue of footer section alignment and navbar responsiveness if you can perform this then i can assign to You

**Comment by Wahid7852** [comment]
> > @ankit071105 You should be more active while assigning issues, Contributors work hard to create one PR and we told them start working only if they get assign, and they do it too.
> > You should not overlook someone's hardwork, you can merge this PR and give her the required labels i.e. level 2 and revert the changes back.
> > As most of the Contributors are beginners they dont know these things are part of the open source, as it is the first time, you may explain them and tell for now you will merge this and from next time you should be prepare that these things will happen in future.
> 
> Who are you brother ? why you invoving in this matter @MastanSayyad . The issue was by mistake assign because daily 30+ issue are raising so it get assigned with the flow with the mentor firstly and you dont guide us what to do you we are providing a experienced label and gssoc and hacktoberfest badges. So please dont teach us .

he's literally the program manager lol.... WDYM "who are you".

**Comment by Hemantlohar** [comment]
> > @ankit071105 You should be more active while assigning issues, Contributors work hard to create one PR and we told them start working only if they get assign, and they do it too.
> > You should not overlook someone's hardwork, you can merge this PR and give her the required labels i.e. level 2 and revert the changes back.
> > As most of the Contributors are beginners they dont know these things are part of the open source, as it is the first time, you may explain them and tell for now you will merge this and from next time you should be prepare that these things will happen in future.
> 
> Who are you brother ? why you invoving in this matter @MastanSayyad . The issue was by mistake assign because daily 30+ issue are raising so it get assigned with the flow with the mentor firstly and you dont guide us what to do you we are providing a experienced label and gssoc and hacktoberfest badges. So please dont teach us .

kisi ko kuch bolne se phle dekh lena chaiye ki agar koi insaan kuch bol raha hai to kisi reason se bol raha hoga , agar vo program manager nhi bhi hai to koi galat baat nhi boli thi bro , and second thing is that thoda respect se baat karo

**Comment by ankit071105** [comment]
> @ankit071105 You should be more active while assigning issues, Contributors work hard to create one PR and we told them start working only if they get assign, and they do it too.
> 
> You should not overlook someone's hardwork, you can merge this PR and give her the required labels i.e. level 2 and revert the changes back.
> 
> As most of the Contributors are beginners they dont know these things are part of the open source, as it is the first time, you may explain them and tell for now you will merge this and from next time you should be prepare that these things will happen in future.

okay bro but the project doesn't need this type our webpage is for only ticket , hotels issue we are not working okay i have merged now from next time i will be more active

**Pull request merged**
