### PR TITLE
Neatly Arranged the content on footer

### LINKED ISSUE #721: neatly arranging the footer content of contact page
Screenshot (61)

I would like to arrange properly the content on footer of contact page and making it more attractive

please!! assign this to me i would like to work on it

### PR DESCRIPTION
**Pull request by DevROHIT11**
## What does this PR do?

I was assigned to task to neatly arrrange the footer content of contact us page , successfully completed the task.

Fixes #721 

Screenshot :-
Screenshot (72)

## Type of change
-neatly arranged the HELPFUL LINKS , ABOUT US , KEEPING SAFE , FIND US ,etc

- [ x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by ankit071105** [comment]
Resolve the conflicts bro

**Comment by DevROHIT11** [comment]
Bro i have doubt regarding the conflicts  can u plz tell me how to resolve it

**Comment by DevROHIT11** [comment]
@ankit071105  I had Resolved the merge conflicts could you please check and accept my pull request

**Comment by ankit071105** [comment]
Resolve the conflicts

**Pull request closed without merging**
