### PR TITLE
Altered the faq 

### PR DESCRIPTION
**Pull request by Mandy1200**
## What does this PR do?

Altered the faq and modified the questions in faq

Fixes #(issue)
Screenshot (127)

## Type of change

- Bug fix (non-breaking change which fixes an issue)- Chore (refactoring code, technical debt, workflow improvements)

## Screenshots 
Screenshot (126)

## Mandatory Tasks

- [✔️ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by ankit071105** [comment]
@MastanSayyad  Don't remove the label he had changed the faq questions fully one of the contributor added the the dummy one from any other webpage and paste the code

**Comment by MastanSayyad** [comment]
@ankit071105 

When a reviewer evaluates a PR, what do they look for? This PR doesn’t have any explanation or reference to the work being done. only two snapshots, You should know that PRs from the leaderboard for each contributor are reviewed by the core team. Assigning a level 2 for 0 additions would be considered spam, wouldn't it?

- I cant find any issue linked to it, nor it is mentioned in PR
- you said he had changed the faq questions fully and one of the contributor added the the dummy one from any other webpage and paste the code so where is the reference for this?

Isn't it the PAs and contributor's responsibility to provide proper explanations so reviewers can get a clear understanding of the work.

doubts were in my mind because I saw you gave multiple labels level 1,2,3 to every PRs of only this contributor

image

You should properly document the issues and PRs. I checked all his PRs and looked for any references to see if there was a related PR to assign a level to, but I found none. there was one more PR about trail effect with same zero code so I looked and found there was one PR for trail effect therefore I gave labels for that, but how can justify these PRs? what will you do when other contributors point it out and claim this contributor as spammer?

Thats why I need proper context as a Program manager I need to check every possibility so that we don't compromise quality of this program!

**Comment by Mandy1200** [comment]
First thing , I know before submitting PR I should have to mention the problem 

But it was mentioned in the issue section , respectfully I always do as per requirement 


Secondly this is the modified UI FAQ , when I submitted the last FAQ their was a dummy(some random questions)  

I had edited the whole FAQ with enhanced CSS and JS but after that it was changed with a new UI

**Comment by MastanSayyad** [comment]
@Mandy1200 This response doesn’t fully address my concerns. I understand that you modified the FAQ and made great changes, which is appreciated. However, please read my questions carefully.

If we review your profile on the leaderboard, on what basis should we consider this PR without proper context? What will you do if other contributors point out the PR and accuse you of spamming?

Here are some things you need to clarify:

- You must mention the assigned issue in your PR so that we can see the task you were working on was officially assigned to you. This also helps us track progress and validate the work.
- If this is indeed a modified version of the FAQ, where are the file changes? This PR shows zero file changes.
- Your PR had multiple levels assigned. Why didn’t you bring it up with us or the PA if you noticed discrepancies in the levels?

It's important to follow these guidelines to ensure that your work is appropriately evaluated and there's no confusion about your contributions.

**Comment by ankit071105** [comment]
> @Mandy1200 This response doesn’t fully address my concerns. I understand that you modified the FAQ and made great changes, which is appreciated. However, please read my questions carefully.
> 
> If we review your profile on the leaderboard, on what basis should we consider this PR without proper context? What will you do if other contributors point out the PR and accuse you of spamming?
> 
> Here are some things you need to clarify:
> 
> * You must mention the assigned issue in your PR so that we can see the task you were working on was officially assigned to you. This also helps us track progress and validate the work.
> * If this is indeed a modified version of the FAQ, where are the file changes? This PR shows zero file changes.the levels should be given to actual file changed PR not these PRs
> * Your PR had multiple levels assigned. Why didn’t you bring it up with us or the PA if you noticed discrepancies in the levels?
> 
> It's important to follow these guidelines to ensure that your work is appropriately evaluated and there's no confusion about your contributions.

Okay Let End This Argue I think We should move on from this @Mandy1200  You contribute We are not accepting this PR , We can not assign you label for this @MastanSayyad  See the issue accept the pr and assign label to others correctly so we can be fair

**Pull request merged**
