### PR TITLE
"Separation of Bus Ticket and Train Ticket Pages for Improved User Navigation"

### PR DESCRIPTION
**Pull request by praveenarjun**
Description of the Solution:

This solution separates the Bus Ticket and Train Ticket options into individual pages. The changes include:

    Creation of a new bus_ticket.html page to display bus ticket options.
    Creation of a new train_ticket.html page to display train ticket options.
    Updated navigation to include links to these separate pages for better user experience and organization.

# from this 
Screenshot 2024-10-02 at 6 00 16 PM

To this
Screenshot 2024-10-02 at 6 00 30 PM
Ad I make changes in index page for the image to fit the page as per window size

### CODE REVIEW

**Comment by praveenarjun** [comment]
Hi team,

I have created separate pages to show the bus ticket and train ticket. If there are any changes needed, please comment so that I can improve as per your needs.
Thank you!

**Comment by skddl007** [comment]
Can we do if the user selects a bus, then only show available bus tickets, just like a train?

**Comment by praveenarjun** [comment]
yes we can do if on click that button then using dom in js using inner html creating a html file on clicking the button

**Comment by skddl007** [comment]
Yaa, I know but it's better way

**Comment by ankit071105** [comment]
https://chat.whatsapp.com/JWfNTvpbNTfDp0zWsgNGWi 
Bro you can join us we will have discussion related to our projects in this group. @praveenarjun

**Pull request merged**
