### PR TITLE
fixed gap, added home link, added same navbar for all pages

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
## What does this PR do?
@ankit071105 
I have removed the extra gap from the icon and the name of the website, and added home link to it for navigation and changes it for all the pages

Kindly check it out

https://github.com/user-attachments/assets/1b8f3553-c585-4cf9-94de-396941ea5b90

Fixes #(issue)

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by AswaniBolisetti** [comment]
@ankit071105 
Please merge this

**Comment by AswaniBolisetti** [comment]
@ankit071105 
Please check this and merge

**Comment by ankit071105** [comment]
Resolve the conflicts

**Comment by AswaniBolisetti** [comment]
@ankit071105 
Resolved conflicts check now

**Pull request merged**
