### PR TITLE
User is registering and logging In successfully

### LINKED ISSUE #213: Users unable to register or log in due to error while fetching response
Users are encountering an error when attempting to register or log in. The issue occurs when fetching the response from the server, resulting in unsuccessful sign-ins. This issue blocks users from accessing their accounts and prevents them from successfully registering. 

**Expected Behavior:**
Users should be able to successfully register or log in and receive a proper response from the server, allowing them access to the application.

**Actual Behavior:**
An error occurs when fetching the response, causing the login or registration to fail. No success message is displayed, and users remain on the login/register page.

Please assign this task to me under **Hectoberfest-accepted and gssoc-ext.** 

image

### PR DESCRIPTION
**Pull request by an-um**
## What does this PR do?

Each time the user were trying to register and login, the connection-rejection error were occuring.

- I resolved the connection error, established a connection between frontend and backend.
- Now, user can register successfully, and redirected to login page
- User can login able access dashboard page(which currently is not available.) 
 

Fixes #213 

## Type of change

- There were connection errors, while fetching the APIs
- Minor syntax issues that were causing the issues
- Established a connection, so that user can register and login successfully.

## Screenshots 
image

image

### CODE REVIEW

**Comment by an-um** [comment]
I have also added ApiError and ApiResponse files insode utils.

**Comment by ankit071105** [comment]
Resolve the conflicts bro

**Comment by an-um** [comment]
I am not able to see any conflicts locally on my branch. Can you resolve these conflict for me or give me write to resolve these conflicts? I will not merge the branch. Just need an access to resolve here. Thank you!!

**Comment by ankit071105** [comment]
Generate another PR without any conflicts

**Pull request closed without merging**
