### PR TITLE
Redesign Logo/fevicon 

### PR DESCRIPTION
**Pull request by Ananya-vastare**
redesigned the logo by inserting a new one that enhances the website feature

### CODE REVIEW

**Comment by ankit071105** [comment]
Have you been this mention the issue number or if you are not assign then follow the rules of GSSOC_EXTEND and HACKTOBERFEST @Ananya-vastare

**Comment by ankit071105** [comment]
Resolve the conflicts @Ananya-vastare

**Comment by Ananya-vastare** [comment]
Can I send it before 5pm please

**Comment by ankit071105** [comment]
> Can I send it before 5pm please

okay @Ananya-vastare

**Comment by Ananya-vastare** [comment]
@ankit071105 I have resolved the conflicts

**Comment by Ananya-vastare** [comment]
Can you add the level to this please

**Pull request merged**
