### PR TITLE
added move to top button and faq section 

### PR DESCRIPTION
**Pull request by govindumeesala**
Added move to top button to website 
Added faq section
Fixed issue of nav logo link not working now nav logo redirects to home

### CODE REVIEW

**Comment by ankit071105** [comment]
There are  conflicts  in the code that must be resolved then only We will accept it @govindumeesala

**Comment by govindumeesala** [comment]
@ankit071105  Heyy I resolved the conflicts and added smooth scroll to the move to top button 
Now check once consider merging this pr

**Comment by govindumeesala** [comment]
@ankit071105 Heyy I resolved the conflicts and added  move to top button since missing 
Now check once consider merging this pr

**Comment by ankit071105** [comment]
https://chat.whatsapp.com/JWfNTvpbNTfDp0zWsgNGWi 
Bro you can join us we will have discussion related to our projects in this group. @govindumeesala

**Pull request merged**
