### PR TITLE
contactus page with the new look

### PR DESCRIPTION
**Pull request by Anu142004**
## What does this PR do?

Fixes #(issue) it has created a new format of html,css of the contact page 

## Type of change

- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by Anu142004** [comment]
ankit071105 pl do review it and accept it and merge it

**Comment by ankit071105** [comment]
Resolve the conflicts

**Comment by Anu142004** [comment]
what is the conflict

**Comment by Anu142004** [comment]
pl do check I have resolved the conflicts

**Pull request merged**
