### PR TITLE
Fixing the Feedbackcards

### PR DESCRIPTION
**Pull request by Mandy1200**
## What does this PR do?

fixed the feedback-cards and added proper answers

Fixes #(issue)
Screenshot (131)

## Type of change

- Chore (refactoring code, technical debt, workflow improvements)

## Mandatory Tasks

- [✔️ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by MastanSayyad** [comment]
Hi @ankit071105 

I noticed that multiple labels have been assigned to the PRs of contributor @Mandy1200. Could you please remove the extra labels? Regardless of the complexity of the work, Level 3 should be the maximum level assigned.

Please add me as a collaborator as soon as possible so I can review and fix the labels based on the changes made in each PR.

I hope there is no unfair practice involved, and these PRs are not spam.

image

**Comment by MastanSayyad** [comment]
Hi @ankit071105 I need answers and this PR can only have `level 2` for such changes 
also, you haven't added me as a collaborator yet! 

image

also you cant add labels to your own PRs, you are project admin, with labels your name will also reflect in the leaderboard!

**Comment by ankit071105** [comment]
> Hi @ankit071105 I need answers and this PR can only have `level 2` for such changes also, you haven't added me as a collaborator yet!
> 
> Are you active on the discord?
> 
> image
> 
> also you cant add labels to your own PRs, you are project admin, with labels your name will also reflect in the leaderboard!

okay i was not aware of that

**Comment by ankit071105** [comment]
I added you before only @MastanSayyad

**Pull request merged**
