### PR TITLE
Duplicate login form fixed And .env file created

### PR DESCRIPTION
**Pull request by riyaaryan2004**
### Reference issue #200 
Bugs in login page are fixed.
And .env file is created.

Screenshot 2024-10-07 020222

Screenshot 2024-10-07 014117

### CODE REVIEW

**Comment by ankit071105** [comment]
Nice work @riyaaryan2004  I want only one more contribution from your side the data which user providing at time of signup that get stored in there personal dashboard . If You can create this work on this . Thank You for your valuable contribution towards open source . @riyaaryan2004

**Comment by riyaaryan2004** [comment]
@ankit071105 

I m getting error whlie doing signup via email.

First I have to fix this issue.
Can I work on this issue
ticket booking signup
Screenshot 2024-10-07 120336

**Comment by ankit071105** [comment]
Yes go ahead 👍🏻 @riyaaryan2004

**Comment by riyaaryan2004** [comment]
@ankit071105  I have fixed some issue .
I want you to know I am working on the issue you put forward.
Will create a raise a PR soon.
Working on more backend issue.
Thank you 
Screenshot 2024-10-08 233715

Screenshot 2024-10-08 233912

**Comment by ankit071105** [comment]
> @ankit071105 I have fixed some issue . I want you to know I am working on the issue you put forward. Will create a raise a PR soon. Working on more backend issue. Thank you Used temporary mongodb url for testing. Here are some screenshots. Screenshot 2024-10-08 233715 Screenshot 2024-10-08 233912 Screenshot 2024-10-08 234629

okay fix if you can create data base you can create an raise an issue

**Pull request merged**
