### PR TITLE
Improve Button Styling and Fix Transitions for Responsive UI

### PR DESCRIPTION
**Pull request by Himanshusingh9647**
### This pull request includes the following changes:

1. Refined the button's gradient and color scheme to match the project’s theme.
2.  Fixed the CSS transition issue by ensuring all properties are properly applied and animated on hover.
3. Ensured responsive and smooth hover effect transitions, along with active and focus states.
4.  Updated box-shadow and padding adjustments for better visual appeal and user interaction.

### CODE REVIEW

**Comment by ankit071105** [comment]
Bro Resolve the conflicts @Himanshusingh9647

**Comment by Himanshusingh9647** [comment]
resolved all the conflicts.

**Comment by Himanshusingh9647** [comment]
Please check all the conflicts resolved

**Comment by ankit071105** [comment]
https://chat.whatsapp.com/JWfNTvpbNTfDp0zWsgNGWi 
Bro you can join us we will have discussion related to our projects in this group. @Himanshusingh9647

**Pull request merged**
