### PR TITLE
 The unnecessary login link Appears #983

### LINKED ISSUE #983: [BUG] The unnecessary login link Appears
### Description

A unnecessary login link and AI suggestion link and the image of  moon also appears between the navbar and the main section's image

### Screenshots

Screenshot 2024-11-05 154855

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by sachinggsingh**
## What does this PR do?
Fixes #983
## Screenshots 
**How it is**
Screenshot 2024-11-06 121959

**How it was**
Screenshot 2024-11-05 154855

### CODE REVIEW

**Comment by ankit071105** [comment]
Resolve the conflicts

**Comment by sachinggsingh** [comment]
> Resolve the conflicts

Sure

**Comment by sachinggsingh** [comment]
@ankit071105  i have resolved the conflicts from my editor and committed the changes kindly look at it

**Comment by sachinggsingh** [comment]
@ankit071105 i have resolved the conflicts from my editor and committed the changes kindly look at it

**Pull request closed without merging**
