### PR TITLE
Enhanced Contact Page Design for Improved UX

### LINKED ISSUE #739: Contact Page Design Enhancement
Enhanced the contact page design for improved aesthetics and usability. A sample layout has been attached as a reference, showcasing the intended structure and style updates. This update aims to create a more cohesive and visually appealing contact page, aligning better with the overall site design and improving user experience.

Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.

image

### PR DESCRIPTION
**Pull request by ritiksingh-01**
## What does this PR do?

This update improves the overall design of the Contact page to create a more user-friendly experience. Adjustments include layout refinements and aesthetic changes that make it easier for users to navigate and engage with the page content. The enhanced design aims to provide a cleaner, more intuitive interface, contributing to a polished and professional appearance across the site.

Fixes #739 

https://github.com/user-attachments/assets/30c788a3-0155-4575-b411-ae714224fbc6

## Type of change

- New feature (non-breaking change which adds functionality)

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by ankit071105** [comment]
Resolve the Conflicts @ritiksingh-01

**Comment by ritiksingh-01** [comment]
> Resolve the Conflicts @ritiksingh-01

Done

**Comment by ritiksingh-01** [comment]
Hi, @ankit071105 

Could you please consider increasing the level of this task? I believe it qualifies as Level 2 work given the complexity involved. Thank you!

**Comment by ritiksingh-01** [comment]
Hi, @ankit071105 
bhai tujhe jab accept hi nahi karna tha to mehnat kyu karaya!!

**Comment by ankit071105** [comment]
> Resolve the Conflicts @ritiksingh-01

bhai jb maine bola tha resolve the file Conflicts to tune kiye he nahi to close krna par mujhe

**Comment by ritiksingh-01** [comment]
> > Resolve the Conflicts @ritiksingh-01
> > bhai jb maine bola tha resolve the file Conflicts to tune kiye he nahi to close krna par mujhe
> 
> # See this
> Screenshot 2024-11-01 at 11 40 14 AM

bhai 2 din le rahe ho accept karne main to conflict to ayega na eske phale aya tha maine sovle kiya apko osko dekhne main 2 din lag gye so aap apna bhi to mistake dekho

**Comment by ankit071105** [comment]
> > > Resolve the Conflicts @ritiksingh-01
> > > bhai jb maine bola tha resolve the file Conflicts to tune kiye he nahi to close krna par mujhe
> > 
> > 
> > # See this
> > Screenshot 2024-11-01 at 11 40 14 AM
> 
> bhai 2 din le rahe ho accept karne main to conflict to ayega na eske phale aya tha maine sovle kiya apko osko dekhne main 2 din lag gye so aap apna bhi to mistake dekho

bhai mai dhek chuka tha tb bhi confltcs show kr rh tha agr nahi krta to merge kr deta sabka PR accept kr rh hu mai tumhara kyu nahi krunga .

**Comment by ritiksingh-01** [comment]
> > > > Resolve the Conflicts @ritiksingh-01
> > > > bhai jb maine bola tha resolve the file Conflicts to tune kiye he nahi to close krna par mujhe
> > > 
> > > 
> > > # See this
> > > Screenshot 2024-11-01 at 11 40 14 AM
> > 
> > 
> > bhai 2 din le rahe ho accept karne main to conflict to ayega na eske phale aya tha maine sovle kiya apko osko dekhne main 2 din lag gye so aap apna bhi to mistake dekho
> 
> bhai mai dhek chuka tha tb bhi confltcs show kr rh tha agr nahi krta to merge kr deta sabka PR accept kr rh hu mai tumhara kyu nahi krunga .

Are bhai aap reopen karo main esko turant solve kar dunga

**Pull request closed without merging**
